permalink: /:year:month:day/:title
url: #Your url here
baseurl: /project

# variables
name: 사비성(sabisung) 폴더
description: 좋은 생각이 나를 바꾼다.<br/><br/>열망하고, 움켜잡고, 유영하라~
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true
